<a href="https://colab.research.google.com/github/Vaibhavbhor404/workshops/blob/main/24March.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
data={
    "Energy source":["Solar","wind","Hydropower","Geothermal","Biomass","Nuclear"],
    "Energy Consuption (MWh)":[1200,np.nan,2900,np.nan,2500,3200],
    "Cost (million $ )":[200,400,np.nan,150,250,np.nan]
}
df=pd.DataFrame(data)
# print(df)
# df.head(3)
df.tail(3)

  Energy source  Energy Consuption (MWh)  Cost (million $ )
3    Geothermal                      NaN              150.0
4       Biomass                   2500.0              250.0
5       Nuclear                   3200.0                NaN

In [10]:
df.shape

(6, 3)

In [13]:
df.describe()

       Energy Consuption (MWh)  Cost (million $ )
count                 4.000000           4.000000
mean               2450.000000         250.000000
std                 881.286938         108.012345
min                1200.000000         150.000000
25%                2175.000000         187.500000
50%                2700.000000         225.000000
75%                2975.000000         287.500000
max                3200.000000         400.000000

In [14]:
df.isnull().sum().sum()

np.int64(4)

In [15]:
cleaned_df=df.dropna()
print(cleaned_df)

  Energy source  Energy Consuption (MWh)  Cost (million $ )
0         Solar                   1200.0              200.0
4       Biomass                   2500.0              250.0

In [16]:
df.columns

Index(['Energy source', 'Energy Consuption (MWh)', 'Cost (million $ )'], dtype='object')

In [17]:
df['Energy Consuption (MWh)'].fillna(df['Energy Consuption (MWh)'].mean(),inplace=True)
df['Cost (million $ )'].fillna(df['Cost (million $ )'].mean(),inplace=True)
print(df)

  Energy source  Energy Consuption (MWh)  Cost (million $ )
0         Solar                   1200.0              200.0
1          wind                   2450.0              400.0
2    Hydropower                   2900.0              250.0
3    Geothermal                   2450.0              150.0
4       Biomass                   2500.0              250.0
5       Nuclear                   3200.0              250.0

/tmp/ipykernel_9182/3551547994.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Energy Consuption (MWh)'].fillna(df['Energy Consuption (MWh)'].mean(),inplace=True)
/tmp/ipykernel_9182/3551547994.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cost (million $ )'].fillna(df['Cost (million $ )'].mean(),inplace=True)

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df[['Energy Consuption (MWh)','Cost (million $ )']]=scaler.fit_transform(df[['Energy Consuption (MWh)','Cost (million $ )']])
print(df)

  Energy source  Energy Consuption (MWh)  Cost (million $ )
0         Solar                    0.000                0.2
1          wind                    0.625                1.0
2    Hydropower                    0.850                0.4
3    Geothermal                    0.625                0.0
4       Biomass                    0.650                0.4
5       Nuclear                    1.000                0.4

In [19]:
import pandas as pd
energy_encoded_df=pd.get_dummies(df,columns=['Energy source'])
print("\nData after one-hot Encoding Categorical variable")
print(energy_encoded_df)

Data after one-hot Encoding Categorical variable
   Energy Consuption (MWh)  Cost (million $ )  Energy source_Biomass  \
0                    0.000                0.2                  False
1                    0.625                1.0                  False
2                    0.850                0.4                  False
3                    0.625                0.0                  False
4                    0.650                0.4                   True
5                    1.000                0.4                  False

   Energy source_Geothermal  Energy source_Hydropower  Energy source_Nuclear  \
0                     False                     False                  False
1                     False                     False                  False
2                     False                      True                  False
3                      True                     False                  False
4                     False                     False                  False
5                     False                     False                   True

   Energy source_Solar  Energy source_wind
0                 True               False
1                False                True
2                False               False
3                False               False
4                False               False
5                False               False

In [20]:
energy_encoded_df['Cost (million $ )']=energy_encoded_df["Energy Consuption (MWh)"]
print("\nData with New Feature (Consuption per $Million) :")
print(energy_encoded_df)

Data with New Feature (Consuption per $Million) :
   Energy Consuption (MWh)  Cost (million $ )  Energy source_Biomass  \
0                    0.000              0.000                  False
1                    0.625              0.625                  False
2                    0.850              0.850                  False
3                    0.625              0.625                  False
4                    0.650              0.650                   True
5                    1.000              1.000                  False

   Energy source_Geothermal  Energy source_Hydropower  Energy source_Nuclear  \
0                     False                     False                  False
1                     False                     False                  False
2                     False                      True                  False
3                      True                     False                  False
4                     False                     False                  False
5                     False                     False                   True

   Energy source_Solar  Energy source_wind
0                 True               False
1                False                True
2                False               False
3                False               False
4                False               False
5                False               False